sudo: required
services:
  - docker

before_install:
  - docker build -t vladstepway/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vladstepway/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-142463805846"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
